/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app.views.respondent;

/**
 *
 * @author iakba
 */
public class LongEssay extends Answer {

  /**
   * Creates new form SingleChoise
   */
  public LongEssay() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    scrollPane = new javax.swing.JScrollPane();
    longEssayAnswer = new javax.swing.JTextArea();
    background = new javax.swing.JLabel();

    setBackground(new java.awt.Color(68, 74, 74));
    setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    longEssayAnswer.setColumns(20);
    longEssayAnswer.setRows(5);
    scrollPane.setViewportView(longEssayAnswer);

    add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 650, 200));

    background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background/quizAnswer.png"))); // NOI18N
    add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-27, -274, 720, 510));
  }// </editor-fold>//GEN-END:initComponents

  /**
   * Mendapatkan answer dari sub-panel
   * @return Mengembalikan jawaban berupa String
   */
  @Override
  public String getAnswer() {
    return longEssayAnswer.getText();
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel background;
  private javax.swing.JTextArea longEssayAnswer;
  private javax.swing.JScrollPane scrollPane;
  // End of variables declaration//GEN-END:variables
}
