/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app.views.respondent;

import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.border.LineBorder;
import org.json.JSONArray;

/**
 *
 * @author iakba
 */
public class SingleChoise extends Answer {
  /**
   * Creates new form SingleChoise
   * @param choises Pilihan jawaban berupa JSONArray
   */
  public SingleChoise(JSONArray choises) {
    initComponents();
    
    firstOptionLabel.setText(choises.getString(0));
    secondOptionLabel.setText(choises.getString(1));
    thirdOptionLabel.setText(choises.getString(2));
    fourthOptionLabel.setText(choises.getString(3));
    
    this.choises.add(firstOption);
    this.choises.add(secondOption);
    this.choises.add(thirdOption);
    this.choises.add(fourthOption);
    
    firstOption.setVisible(false);
    secondOption.setVisible(false);
    thirdOption.setVisible(false);
    fourthOption.setVisible(false);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    choises = new javax.swing.ButtonGroup();
    firstOptionPanel = new javax.swing.JPanel();
    firstOptionLabel = new javax.swing.JLabel();
    secondOptionPanel = new javax.swing.JPanel();
    secondOptionLabel = new javax.swing.JLabel();
    thirdOptionPanel = new javax.swing.JPanel();
    thirdOptionLabel = new javax.swing.JLabel();
    fourthOptionPanel = new javax.swing.JPanel();
    fourthOptionLabel = new javax.swing.JLabel();
    firstOption = new javax.swing.JRadioButton();
    secondOption = new javax.swing.JRadioButton();
    thirdOption = new javax.swing.JRadioButton();
    fourthOption = new javax.swing.JRadioButton();
    background = new javax.swing.JLabel();

    setBackground(new java.awt.Color(68, 74, 74));
    setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    firstOptionPanel.setBackground(new java.awt.Color(182, 99, 212));
    firstOptionPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    firstOptionPanel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        firstOptionPanelMouseClicked(evt);
      }
    });
    firstOptionPanel.setLayout(new java.awt.BorderLayout());

    firstOptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    firstOptionLabel.setText("abc");
    firstOptionPanel.add(firstOptionLabel, java.awt.BorderLayout.CENTER);

    add(firstOptionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 100, 100));

    secondOptionPanel.setBackground(new java.awt.Color(182, 99, 212));
    secondOptionPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    secondOptionPanel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        secondOptionPanelMouseClicked(evt);
      }
    });
    secondOptionPanel.setLayout(new java.awt.BorderLayout());

    secondOptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    secondOptionLabel.setText("abc");
    secondOptionPanel.add(secondOptionLabel, java.awt.BorderLayout.CENTER);

    add(secondOptionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 100, 100));

    thirdOptionPanel.setBackground(new java.awt.Color(182, 99, 212));
    thirdOptionPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    thirdOptionPanel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        thirdOptionPanelMouseClicked(evt);
      }
    });
    thirdOptionPanel.setLayout(new java.awt.BorderLayout());

    thirdOptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    thirdOptionLabel.setText("abc");
    thirdOptionPanel.add(thirdOptionLabel, java.awt.BorderLayout.CENTER);

    add(thirdOptionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 100, 100));

    fourthOptionPanel.setBackground(new java.awt.Color(182, 99, 212));
    fourthOptionPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    fourthOptionPanel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        fourthOptionPanelMouseClicked(evt);
      }
    });
    fourthOptionPanel.setLayout(new java.awt.BorderLayout());

    fourthOptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    fourthOptionLabel.setText("abc");
    fourthOptionPanel.add(fourthOptionLabel, java.awt.BorderLayout.CENTER);

    add(fourthOptionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 100, 100));
    add(firstOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));
    add(secondOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));
    add(thirdOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));
    add(fourthOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, -1, -1));

    background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background/quizAnswer.png"))); // NOI18N
    add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-27, -274, 720, 510));
  }// </editor-fold>//GEN-END:initComponents

  private void updateChoises(JRadioButton active){
    firstOption.setSelected(false);
    secondOption.setSelected(false);
    thirdOption.setSelected(false);
    fourthOption.setSelected(false);
    
    active.setSelected(true);
  }
  
  private void updatePanel(JPanel active){
    firstOptionPanel.setBorder(null);
    secondOptionPanel.setBorder(null);
    thirdOptionPanel.setBorder(null);
    fourthOptionPanel.setBorder(null);
    
    active.setBorder(new LineBorder(new Color(255, 255, 255), 2, true));
  }
  
  private void firstOptionPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstOptionPanelMouseClicked
    updateChoises(firstOption);
    updatePanel(firstOptionPanel);
  }//GEN-LAST:event_firstOptionPanelMouseClicked

  private void secondOptionPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_secondOptionPanelMouseClicked
    updateChoises(secondOption);
    updatePanel(secondOptionPanel);
  }//GEN-LAST:event_secondOptionPanelMouseClicked

  private void thirdOptionPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thirdOptionPanelMouseClicked
    updateChoises(thirdOption);
    updatePanel(thirdOptionPanel);
  }//GEN-LAST:event_thirdOptionPanelMouseClicked

  private void fourthOptionPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourthOptionPanelMouseClicked
    updateChoises(fourthOption);
    updatePanel(fourthOptionPanel);
  }//GEN-LAST:event_fourthOptionPanelMouseClicked

  /**
   * Mendapatkan answer dari sub-panel
   * @return Mengembalikan jawaban berupa Integer
   */
  @Override
  public Integer getAnswer() {
    if(firstOption.isSelected()) return 0;
    if(secondOption.isSelected()) return 1;
    if(thirdOption.isSelected()) return 2;
    if(fourthOption.isSelected()) return 3;
    return -1;
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel background;
  private javax.swing.ButtonGroup choises;
  private javax.swing.JRadioButton firstOption;
  private javax.swing.JLabel firstOptionLabel;
  private javax.swing.JPanel firstOptionPanel;
  private javax.swing.JRadioButton fourthOption;
  private javax.swing.JLabel fourthOptionLabel;
  private javax.swing.JPanel fourthOptionPanel;
  private javax.swing.JRadioButton secondOption;
  private javax.swing.JLabel secondOptionLabel;
  private javax.swing.JPanel secondOptionPanel;
  private javax.swing.JRadioButton thirdOption;
  private javax.swing.JLabel thirdOptionLabel;
  private javax.swing.JPanel thirdOptionPanel;
  // End of variables declaration//GEN-END:variables
}
