/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app.views.host;

import java.awt.Color;

/**
 *
 * @author User
 */
public class CreateQuizCard extends javax.swing.JPanel {

  /**
   * Creates new form CreateQuizCard
   */
  public CreateQuizCard() {
    initComponents();
    setBackground(new Color(0,0,0,0));
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    container = new javax.swing.JLabel();

    setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    container.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background/CreateQuizCard.png"))); // NOI18N
    add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel container;
  // End of variables declaration//GEN-END:variables
}
