/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app.views.host;

/**
 *
 * @author User
 */
public class CreateQuiz extends javax.swing.JPanel {

  /**
   * Creates new form CreayeQuiz
   */
  public CreateQuiz() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroup1 = new javax.swing.ButtonGroup();
    radioYAbtn = new javax.swing.JRadioButton();
    radioTIDAKbtn = new javax.swing.JRadioButton();
    homeBtn = new javax.swing.JLabel();
    saveBtn = new javax.swing.JLabel();
    addBtn = new javax.swing.JLabel();
    judulLabel = new javax.swing.JLabel();
    idLabel = new javax.swing.JLabel();
    penBtn = new javax.swing.JLabel();
    copyBtn = new javax.swing.JLabel();
    createQuizBG = new javax.swing.JLabel();

    setBackground(new java.awt.Color(68, 74, 74));
    setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    buttonGroup1.add(radioYAbtn);
    add(radioYAbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 64, 30, -1));

    buttonGroup1.add(radioTIDAKbtn);
    add(radioTIDAKbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 64, 30, -1));

    homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/homeIcon.png"))); // NOI18N
    add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 24, -1, -1));

    saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/saveIcon.png"))); // NOI18N
    add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 27, -1, -1));

    addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/tambahBtn.png"))); // NOI18N
    add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 420, 110, 50));

    judulLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 28)); // NOI18N
    judulLabel.setText("judul");
    add(judulLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

    idLabel.setFont(new java.awt.Font("Comic Sans MS", 2, 16)); // NOI18N
    idLabel.setForeground(new java.awt.Color(102, 102, 102));
    idLabel.setText("id:");
    add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 60, -1, -1));

    penBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/pen.png"))); // NOI18N
    add(penBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

    copyBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/copy.png"))); // NOI18N
    add(copyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 58, 20, 30));

    createQuizBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background/createQuizBG.png"))); // NOI18N
    add(createQuizBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel addBtn;
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JLabel copyBtn;
  private javax.swing.JLabel createQuizBG;
  private javax.swing.JLabel homeBtn;
  private javax.swing.JLabel idLabel;
  private javax.swing.JLabel judulLabel;
  private javax.swing.JLabel penBtn;
  private javax.swing.JRadioButton radioTIDAKbtn;
  private javax.swing.JRadioButton radioYAbtn;
  private javax.swing.JLabel saveBtn;
  // End of variables declaration//GEN-END:variables
}
