/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app.views.host;

/**
 *
 * @author iakba
 */
public class Dashboard extends javax.swing.JPanel {

  /**
   * Creates new form Dashboard
   */
  public Dashboard() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    nameField = new javax.swing.JTextField();
    btnLogout = new javax.swing.JLabel();
    background = new javax.swing.JLabel();

    setBackground(new java.awt.Color(68, 74, 74));
    setMinimumSize(new java.awt.Dimension(799, 527));
    setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    nameField.setFont(new java.awt.Font("MS UI Gothic", 1, 28)); // NOI18N
    nameField.setText("Ucup");
    nameField.setBorder(null);
    nameField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
    add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 22, 220, -1));

    btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/dashboard-logout-btn.png"))); // NOI18N
    btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        btnLogoutMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        btnLogoutMouseExited(evt);
      }
      public void mousePressed(java.awt.event.MouseEvent evt) {
        btnLogoutMousePressed(evt);
      }
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        btnLogoutMouseReleased(evt);
      }
    });
    add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 458, -1, -1));

    background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background/dashboard.png"))); // NOI18N
    add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
  }// </editor-fold>//GEN-END:initComponents

  private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
    btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/dashboard-logout-btn-hover.png")));
  }//GEN-LAST:event_btnLogoutMouseEntered

  private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
    btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/dashboard-logout-btn.png")));
  }//GEN-LAST:event_btnLogoutMouseExited

  private void btnLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMousePressed
    btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/dashboard-logout-btn-press.png")));
  }//GEN-LAST:event_btnLogoutMousePressed

  private void btnLogoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseReleased
    btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/dashboard-logout-btn.png")));
  }//GEN-LAST:event_btnLogoutMouseReleased


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel background;
  private javax.swing.JLabel btnLogout;
  private javax.swing.JTextField nameField;
  // End of variables declaration//GEN-END:variables
}
