/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app.views.host;

import app.models.Question;
import app.models.Respondent;
import java.util.LinkedList;
import org.json.JSONObject;

/**
 *
 * @author iakba
 */
public class EssayCheck extends javax.swing.JPanel {
  private final int answerIndex;
  private final int respondentIndex;
  private final LinkedList<JSONObject> quizAnswer;
  private int score = 0;
  
  /**
   * Creates new form EssayCheck
   */
  public EssayCheck(String question, int answerIndex, int respondentIndex) {
    initComponents();
    
    this.answerIndex = answerIndex;
    this.respondentIndex = respondentIndex;
    this.question.setText(question);
    
    quizAnswer = Score.getQuizAnswer();
    answer.setText(quizAnswer.get(answerIndex).getString("answer"));
    
    switch(quizAnswer.get(answerIndex).getInt("state")){
      case -1 ->
        answer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
      case 0 ->
        answer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
      case 1 ->
        answer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));
    }
  }
  
  private void updateStatus(int status){
    JSONObject respondent = Score.getRespondent(respondentIndex);
    respondent.put("quizAnswer", quizAnswer);
    
    JSONObject newQuizAnswer = quizAnswer
            .get(answerIndex)
            .put("state", status);
    
    quizAnswer.set(answerIndex, newQuizAnswer);
    
    int score = respondent.getInt("score");
    int grade = new Question()
            .get(quizAnswer
                    .get(answerIndex)
                    .getString("questionId"))
            .getInt("grade");
    
    if(status == 1 && this.score == 0){
      score += grade;
      this.score = grade;
    }
    else if(status == -1 && this.score != 0){
      score -= this.score != 0 ? grade : 0;
      this.score = 0;
    }
    
    respondent.put("score", score);
    
    new Respondent().update(respondent, respondent.getString("_id"));
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    question = new javax.swing.JLabel();
    btnTrue = new javax.swing.JLabel();
    btnFalse = new javax.swing.JLabel();
    scrollPane = new javax.swing.JScrollPane();
    answer = new javax.swing.JTextArea();

    question.setText("jLabel1");

    btnTrue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/true.png"))); // NOI18N
    btnTrue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnTrue.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnTrueMouseClicked(evt);
      }
    });

    btnFalse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/false.png"))); // NOI18N
    btnFalse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnFalse.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnFalseMouseClicked(evt);
      }
    });

    answer.setEditable(false);
    answer.setColumns(20);
    answer.setLineWrap(true);
    answer.setRows(5);
    answer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    scrollPane.setViewportView(answer);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(22, 22, 22)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(question)
          .addGroup(layout.createSequentialGroup()
            .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

              .addComponent(btnTrue)
              .addComponent(btnFalse))))
        .addContainerGap(46, Short.MAX_VALUE))

    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(19, 19, 19)
        .addComponent(question)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()

            .addComponent(btnTrue)
            .addGap(26, 26, 26)
            .addComponent(btnFalse))
          .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(20, Short.MAX_VALUE))

    );
  }// </editor-fold>//GEN-END:initComponents

  private void btnTrueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrueMouseClicked
    updateStatus(1);
    answer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));
  }//GEN-LAST:event_btnTrueMouseClicked

  private void btnFalseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFalseMouseClicked
    updateStatus(-1);
    answer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
  }//GEN-LAST:event_btnFalseMouseClicked

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextArea answer;
  private javax.swing.JLabel btnFalse;
  private javax.swing.JLabel btnTrue;
  private javax.swing.JLabel question;
  private javax.swing.JScrollPane scrollPane;
  // End of variables declaration//GEN-END:variables
}
