/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app.views.host;

/**
 *
 * @author iakba
 */
public class Home extends javax.swing.JPanel {

  /**
   * Creates new form Home
   */
  public Home() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    btnJoin = new javax.swing.JLabel();
    btnLogin = new javax.swing.JLabel();
    optionalField = new javax.swing.JTextField();
    nameField = new javax.swing.JTextField();
    codeField = new javax.swing.JTextField();
    background = new javax.swing.JLabel();

    setBackground(new java.awt.Color(68, 74, 74));
    setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    btnJoin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/home-join-btn.png"))); // NOI18N
    btnJoin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnJoin.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        btnJoinMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        btnJoinMouseExited(evt);
      }
      public void mousePressed(java.awt.event.MouseEvent evt) {
        btnJoinMousePressed(evt);
      }
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        btnJoinMouseReleased(evt);
      }
    });
    add(btnJoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 373, -1, -1));

    btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/home-login-btn.png"))); // NOI18N
    btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 20, -1, -1));
    add(optionalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 316, 181, 29));
    add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 252, 181, 29));
    add(codeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 186, 181, 29));

    background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background/home.png"))); // NOI18N
    add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
  }// </editor-fold>//GEN-END:initComponents

  private void btnJoinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJoinMouseEntered
    btnJoin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/home-join-btn-hover.png")));
  }//GEN-LAST:event_btnJoinMouseEntered

  private void btnJoinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJoinMouseExited
    btnJoin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/home-join-btn.png")));
  }//GEN-LAST:event_btnJoinMouseExited

  private void btnJoinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJoinMousePressed
    btnJoin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/home-join-btn-press.png")));
  }//GEN-LAST:event_btnJoinMousePressed

  private void btnJoinMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJoinMouseReleased
    btnJoin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/home-join-btn.png")));
  }//GEN-LAST:event_btnJoinMouseReleased


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel background;
  private javax.swing.JLabel btnJoin;
  private javax.swing.JLabel btnLogin;
  private javax.swing.JTextField codeField;
  private javax.swing.JTextField nameField;
  private javax.swing.JTextField optionalField;
  // End of variables declaration//GEN-END:variables
}
