/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app.views.host;

import app.Controller;
import app.models.Model;
import app.models.Quiz;
import app.models.User;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.bson.Document;

/**
 *
 * @author iakba
 */
public class Home extends javax.swing.JPanel {

  /**
   * Creates new form Home
   *
   */
  public Home() {
    initComponents();
    Controller.setFrameTitle("Quiz Master - Home");
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    btnJoin = new javax.swing.JLabel();
    btnLogin = new javax.swing.JLabel();
    optionalField = new javax.swing.JTextField();
    nameField = new javax.swing.JTextField();
    codeField = new javax.swing.JTextField();
    background = new javax.swing.JLabel();

    setBackground(new java.awt.Color(68, 74, 74));
    setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    btnJoin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/home-join-btn.png"))); // NOI18N
    btnJoin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnJoin.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnJoinMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        btnJoinMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        btnJoinMouseExited(evt);
      }
      public void mousePressed(java.awt.event.MouseEvent evt) {
        btnJoinMousePressed(evt);
      }
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        btnJoinMouseReleased(evt);
      }
    });
    add(btnJoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 373, -1, -1));

    btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/home-login-btn.png"))); // NOI18N
    btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnLoginMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        btnLoginMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        btnLoginMouseExited(evt);
      }
      public void mousePressed(java.awt.event.MouseEvent evt) {
        btnLoginMousePressed(evt);
      }
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        btnLoginMouseReleased(evt);
      }
    });
    add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 20, -1, -1));
    add(optionalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 316, 181, 29));
    add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 252, 181, 29));
    add(codeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 186, 181, 29));

    background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background/home.png"))); // NOI18N
    add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
  }// </editor-fold>//GEN-END:initComponents

  private void btnJoinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJoinMouseEntered
    btnJoin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/home-join-btn-hover.png")));
  }//GEN-LAST:event_btnJoinMouseEntered

  private void btnJoinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJoinMouseExited
    btnJoin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/home-join-btn.png")));
  }//GEN-LAST:event_btnJoinMouseExited

  private void btnJoinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJoinMousePressed
    btnJoin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/home-join-btn-press.png")));
  }//GEN-LAST:event_btnJoinMousePressed

  private void btnJoinMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJoinMouseReleased
    btnJoin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/home-join-btn.png")));
  }//GEN-LAST:event_btnJoinMouseReleased

  private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
    File fileRemember = new File("cache/remember.txt");
    if (fileRemember.exists() && fileRemember.canRead()) {
      System.out.println("IM HERE");
      List<String> dataRemember = remember();
      Model users = new User();
      if (users.get(new Document()
              .append("username", dataRemember.get(0))
              .append("password", dataRemember.get(1))) != null) {
//       private static USER =  users.get(new Document()
//              .append("username", dataRemember.get(0))
//              .append("password", dataRemember.get(1)));
        Controller.setPanel(new Dashboard());
      } else {
        FileWriter fw;
        try {
          fw = new FileWriter("cache/remember.txt");
          fw.close();
        } catch (IOException ex) {
        }
        Controller.setPanel(new Login());
      }
    } else {
      Controller.setPanel(new Login());
    }
  }//GEN-LAST:event_btnLoginMouseClicked

  private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
    btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/home-login-btn-hover.png")));
  }//GEN-LAST:event_btnLoginMouseEntered

  private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
    btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/home-login-btn.png")));
  }//GEN-LAST:event_btnLoginMouseExited

  private void btnLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMousePressed
    btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/home-login-btn-click.png")));
  }//GEN-LAST:event_btnLoginMousePressed

  private void btnLoginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseReleased
    btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/home-login-btn.png")));
  }//GEN-LAST:event_btnLoginMouseReleased

  private void btnJoinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJoinMouseClicked
    Model quiz = new Quiz();
    System.out.println(quiz.get());
    if(quiz.get("code", codeField.getText()) != null) 
        Controller.showInformationDialog("Anda berhasil masuk bray!", "We did it!!!");
//      Controller.setPanel(QuizPage);
    else Controller.showErrorDialog("Kode yang anda masukkan salah!");
  }//GEN-LAST:event_btnJoinMouseClicked

  public List<String> remember() {
    try {
      List<String> dataRemember = new ArrayList<String>();
      BufferedReader dataUser = new BufferedReader(new FileReader("cache/remember.txt"));
      String line = dataUser.readLine();
      while (line != null) {
        dataRemember.add(line);
        line = dataUser.readLine();
      }
      dataUser.close();
      return dataRemember;
    } catch (Exception e) {
      System.out.println(e);
      return null;
    }
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel background;
  private javax.swing.JLabel btnJoin;
  private javax.swing.JLabel btnLogin;
  private javax.swing.JTextField codeField;
  private javax.swing.JTextField nameField;
  private javax.swing.JTextField optionalField;
  // End of variables declaration//GEN-END:variables
}
