/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app.views.host;

/**
 *
 * @author User
 */
public class Score extends javax.swing.JPanel {

  /**
   * Creates new form Score
   */
  public Score() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    scoreTable = new javax.swing.JTable();
    closeBtn = new javax.swing.JLabel();
    scoreBg = new javax.swing.JLabel();

    setMinimumSize(new java.awt.Dimension(799, 527));
    setPreferredSize(new java.awt.Dimension(799, 527));
    setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    scoreTable.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "No.", "Info", "Nama", "Score"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, false, false, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    scoreTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    scoreTable.setGridColor(new java.awt.Color(217, 217, 217));
    scoreTable.setSelectionBackground(new java.awt.Color(204, 204, 204));
    scoreTable.setShowGrid(true);
    scoreTable.getTableHeader().setResizingAllowed(false);
    scoreTable.getTableHeader().setReorderingAllowed(false);
    jScrollPane1.setViewportView(scoreTable);
    if (scoreTable.getColumnModel().getColumnCount() > 0) {
      scoreTable.getColumnModel().getColumn(0).setResizable(false);
      scoreTable.getColumnModel().getColumn(1).setResizable(false);
      scoreTable.getColumnModel().getColumn(2).setResizable(false);
      scoreTable.getColumnModel().getColumn(3).setResizable(false);
    }

    add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 690, 350));

    closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/close.png"))); // NOI18N
    add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(688, 28, 60, 50));

    scoreBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background/score.png"))); // NOI18N
    scoreBg.setMinimumSize(new java.awt.Dimension(799, 527));
    scoreBg.setPreferredSize(new java.awt.Dimension(799, 527));
    add(scoreBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 527));
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel closeBtn;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel scoreBg;
  private javax.swing.JTable scoreTable;
  // End of variables declaration//GEN-END:variables
}
