/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app.views.host;

import org.json.JSONObject;

/**
 *
 * @author User
 */
public class ShortEssayCard extends javax.swing.JPanel {

  /**
   * Creates new form tunggalCard
   */
  public ShortEssayCard(CreateQuizCard card) {
    initComponents();
    
    card.answers = fieldIsianSingkat;
    
  }
  
  public ShortEssayCard(CreateQuizCard card, JSONObject data){
    this(card);
    if(data.getString("type").equals("ShortEssay")){
      String correctAnswer = data.getJSONObject("answer").getString("correctAnswer");
      fieldIsianSingkat.setText(correctAnswer);
    }
  }
  
  public String getAnswer(){
    return fieldIsianSingkat.getText();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    fieldIsianSingkat = new javax.swing.JTextField();

    setBackground(new java.awt.Color(255, 255, 255));
    setPreferredSize(new java.awt.Dimension(487, 170));
    setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    add(fieldIsianSingkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 210, 30));
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField fieldIsianSingkat;
  // End of variables declaration//GEN-END:variables
}
