/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import app.views.host.Home;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author iakba
 */
public class Controller extends JFrame {
  private static JFrame controller;

  /**
   * Creates new form Controller
   */
  public Controller() {
    initComponents();
    
    controller = this;
    container.add(new Home());
  }

  public static void setPanel(JPanel panel) {
    container.add(panel);
    container.remove(0);
  }
  
  public static void setFrameTitle(String title){
    controller.setTitle(title);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    container = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Quiz Master");
    setPreferredSize(new java.awt.Dimension(814, 566));
    setResizable(false);
    setSize(new java.awt.Dimension(814, 566));

    container.setLayout(new java.awt.CardLayout());

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private static javax.swing.JPanel container;
  // End of variables declaration//GEN-END:variables
}
