/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app;

import app.models.Model;
import app.models.Quiz;
import app.models.User;
import app.views.host.Dashboard;
import app.auth.Login;
import app.views.respondent.QuizAnswer;
import java.awt.AWTException;
import java.awt.Robot;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.json.JSONObject;


/**
 *
 * @author iakba
 */
public class Home extends javax.swing.JPanel {

  /**
   * Creates new form Home
   *
   */
  public Home() {
    initComponents();
    Controller.setFrameTitle("Quiz Master - Home");
    
    optionalField.setVisible(false);
    optionalLabel.setVisible(false);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    optionalLabel = new javax.swing.JLabel();
    nameLabel = new javax.swing.JLabel();
    codeLabel = new javax.swing.JLabel();
    btnJoin = new javax.swing.JLabel();
    btnLogin = new javax.swing.JLabel();
    optionalField = new javax.swing.JTextField();
    nameField = new javax.swing.JTextField();
    codeField = new javax.swing.JTextField();
    title = new javax.swing.JLabel();
    card = new javax.swing.JLabel();
    background = new javax.swing.JLabel();

    setBackground(new java.awt.Color(68, 74, 74));
    setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    optionalLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
    optionalLabel.setForeground(new java.awt.Color(255, 255, 255));
    optionalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    add(optionalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 295, 181, 16));

    nameLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
    nameLabel.setForeground(new java.awt.Color(255, 255, 255));
    nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    nameLabel.setText("Nama");
    add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 230, 181, -1));

    codeLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
    codeLabel.setForeground(new java.awt.Color(255, 255, 255));
    codeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    codeLabel.setText("Kode");
    add(codeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 165, 181, -1));

    btnJoin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/home-join-btn.png"))); // NOI18N
    btnJoin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnJoin.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnJoinMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        btnJoinMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        btnJoinMouseExited(evt);
      }
      public void mousePressed(java.awt.event.MouseEvent evt) {
        btnJoinMousePressed(evt);
      }
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        btnJoinMouseReleased(evt);
      }
    });
    add(btnJoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 309, -1, -1));

    btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/home-login-btn.png"))); // NOI18N
    btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnLoginMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        btnLoginMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        btnLoginMouseExited(evt);
      }
      public void mousePressed(java.awt.event.MouseEvent evt) {
        btnLoginMousePressed(evt);
      }
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        btnLoginMouseReleased(evt);
      }
    });
    add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 20, -1, -1));
    add(optionalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 316, 181, 29));
    add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 252, 181, 29));

    codeField.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        codeFieldKeyReleased(evt);
      }
      public void keyTyped(java.awt.event.KeyEvent evt) {
        codeFieldKeyTyped(evt);
      }
    });
    add(codeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 186, 181, 29));

    title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background/home-title.png"))); // NOI18N
    add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 130, 181, -1));

    card.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background/home-card.png"))); // NOI18N
    add(card, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 110, -1, 266));
    btnJoin.setLocation(btnJoin.getX(), 309);
    card.setSize(card.getWidth(), 266);

    background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background/home.png"))); // NOI18N
    add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
  }// </editor-fold>//GEN-END:initComponents

  private void btnJoinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJoinMouseEntered
    btnJoin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/home-join-btn-hover.png")));
  }//GEN-LAST:event_btnJoinMouseEntered

  private void btnJoinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJoinMouseExited
    btnJoin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/home-join-btn.png")));
  }//GEN-LAST:event_btnJoinMouseExited

  private void btnJoinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJoinMousePressed
    btnJoin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/home-join-btn-press.png")));
  }//GEN-LAST:event_btnJoinMousePressed

  private void btnJoinMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJoinMouseReleased
    btnJoin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/home-join-btn.png")));
  }//GEN-LAST:event_btnJoinMouseReleased

  private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
    if(Login.getUSER() != null){Controller.setPanel(new Dashboard()); return;}
    
    File fileRemember = new File("cache/remember.txt");
    if (!fileRemember.exists()){Controller.setPanel(new Login()); return;}
    
    List<String> dataRemember = remember();
    if(dataRemember.isEmpty()){Controller.setPanel(new Login()); return;} 
    
    Model users = new User();
    JSONObject user = users.get(new JSONObject()
                      .put("username", dataRemember.get(0))
                      .put("password", dataRemember.get(1)));
    if (user == null) {
      try (FileWriter fw = new FileWriter("cache/remember.txt")){}catch(IOException ex){}
      Controller.setPanel(new Login());
      return;
    } 
    Login.setUSER(user);
    Controller.setPanel(new Dashboard());
  }//GEN-LAST:event_btnLoginMouseClicked

  private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
    btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/home-login-btn-hover.png")));
  }//GEN-LAST:event_btnLoginMouseEntered

  private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
    btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/home-login-btn.png")));
  }//GEN-LAST:event_btnLoginMouseExited

  private void btnLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMousePressed
    btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/home-login-btn-click.png")));
  }//GEN-LAST:event_btnLoginMousePressed

  private void btnLoginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseReleased
    btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button/home-login-btn.png")));
  }//GEN-LAST:event_btnLoginMouseReleased

  private void btnJoinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJoinMouseClicked
    if(codeField.getText().equals("")){
      Controller.showErrorDialog("Kode harus diisi!");
      return;
    }
    
    if(nameField.getText().equals("")){
      Controller.showErrorDialog("Nama harus diisi!");
      return;
    }
    
    if(optionalField.isVisible() && optionalField.getText().equals("")){
      JSONObject quiz = new Quiz().get("code", codeField.getText());
      Controller.showErrorDialog(quiz.getString("optField") + " harus diisi!");
      return;
    }
    
    Model quiz = new Quiz();
    JSONObject findQuiz = quiz.get("code", codeField.getText());
    
    if(findQuiz == null){
      Controller.showErrorDialog("Kode yang anda masukkan salah!");
      return;
    }
    
    if(findQuiz.getJSONArray("questions").length() == 0){
      Controller.showInformationDialog(
              "Quiz ini tidak memiliki pertanyaan!\n" +
              "Silakan hubungi pembuat Quiz",
              "Gagal masuk Quiz"
      );
      
      return;
    }
    
    JSONObject respondent = new JSONObject()
            .put("name", nameField.getText())
            .put("optFieldValue", optionalField.getText());
    
    if (Controller.showConfirmDialog("Quiz akan dimulai\nApakah Anda siap?") == 0) { 
      Controller.setPanel(new QuizAnswer(findQuiz, respondent));
    }
    
  }//GEN-LAST:event_btnJoinMouseClicked

  private void codeFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codeFieldKeyTyped
    if(codeField.getText().length() >= 5) evt.consume();
  }//GEN-LAST:event_codeFieldKeyTyped

  private void codeFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codeFieldKeyReleased
    if(codeField.getText().length() >= 5){
      JSONObject quiz = new Quiz().get("code", codeField.getText());
      
      if(quiz != null && !quiz.getString("optField").equals("")){
        optionalField.setVisible(true);
        optionalLabel.setVisible(true);
        optionalLabel.setText(quiz.getString("optField"));
        btnJoin.setLocation(btnJoin.getX(), 373);
        card.setSize(card.getWidth(), 330);

        try {
          Robot robot = new Robot();
          robot.keyPress(KeyEvent.VK_SHIFT);
          robot.keyRelease(KeyEvent.VK_SHIFT);
        } catch (AWTException ex) {
          Controller.showErrorDialog("Terjadi error saat memproses kode!");
        }
        
        return;
      }
    }
    
    optionalField.setVisible(false);
    optionalLabel.setVisible(false);
    optionalLabel.setText("");
    btnJoin.setLocation(btnJoin.getX(), 309);
    card.setSize(card.getWidth(), 266);
  }//GEN-LAST:event_codeFieldKeyReleased

  public List<String> remember() {
    try(BufferedReader dataUser = new BufferedReader(new FileReader("cache/remember.txt"))){
      List<String> dataRemember = new ArrayList<>();
      String line = dataUser.readLine();
      
      while (line != null) {
        dataRemember.add(line);
        line = dataUser.readLine();
      }dataUser.close();
      
      return dataRemember;
      
    } catch (IOException e) {
      Controller.showErrorDialog("Terjadi kesalahan saat mengambil data!");
    }
    
    return null;
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel background;
  private javax.swing.JLabel btnJoin;
  private javax.swing.JLabel btnLogin;
  private javax.swing.JLabel card;
  private javax.swing.JTextField codeField;
  private javax.swing.JLabel codeLabel;
  private javax.swing.JTextField nameField;
  private javax.swing.JLabel nameLabel;
  private javax.swing.JTextField optionalField;
  private javax.swing.JLabel optionalLabel;
  private javax.swing.JLabel title;
  // End of variables declaration//GEN-END:variables
}
